export const sounds = [
  {
    letter: "Q",
    name1: "Heater 1",
    name2: "Chord 1",
    sound1: "https://s3.amazonaws.com/freecodecamp/drums/Heater-1.mp3",
    sound2: "https://s3.amazonaws.com/freecodecamp/drums/Chord_1.mp3",
  },
  {
    letter: "W",
    name1: "Heater 2",
    name2: "Chord 2",
    sound1: "https://s3.amazonaws.com/freecodecamp/drums/Heater-2.mp3",
    sound2: "https://s3.amazonaws.com/freecodecamp/drums/Chord_2.mp3",
  },
  {
    letter: "E",
    name1: "Heater 3",
    name2: "Chord 3",
    sound1: "https://s3.amazonaws.com/freecodecamp/drums/Heater-3.mp3",
    sound2: "https://s3.amazonaws.com/freecodecamp/drums/Chord_3.mp3",
  },
  {
    letter: "A",
    name1: "Heater 4",
    name2: "Shaker",
    sound1: "https://s3.amazonaws.com/freecodecamp/drums/Heater-4_1.mp3",
    sound2: "https://s3.amazonaws.com/freecodecamp/drums/Give_us_a_light.mp3",
  },
  {
    letter: "S",
    name1: "Clap",
    name2: "Open HH",
    sound1: "https://s3.amazonaws.com/freecodecamp/drums/Heater-6.mp3",
    sound2: "https://s3.amazonaws.com/freecodecamp/drums/Dry_Ohh.mp3",
  },
  {
    letter: "D",
    name1: "Open HH",
    name2: "Closed HH",
    sound1: "https://s3.amazonaws.com/freecodecamp/drums/Dsc_Oh.mp3",
    sound2: "https://s3.amazonaws.com/freecodecamp/drums/Bld_H1.mp3",
  },
  {
    letter: "Z",
    name1: "Kick n'Hat",
    name2: "Punchy Kick",
    sound1: "https://s3.amazonaws.com/freecodecamp/drums/Kick_n_Hat.mp3",
    sound2: "https://s3.amazonaws.com/freecodecamp/drums/punchy_kick_1.mp3",
  },
  {
    letter: "X",
    name1: "Kick",
    name2: "Side Kick",
    sound1: "https://s3.amazonaws.com/freecodecamp/drums/RP4_KICK_1.mp3",
    sound2: "https://s3.amazonaws.com/freecodecamp/drums/side_stick_1.mp3",
  },
  {
    letter: "C",
    name1: "Closed HH",
    name2: "Snare",
    sound1: "https://s3.amazonaws.com/freecodecamp/drums/Cev_H2.mp3",
    sound2: "https://s3.amazonaws.com/freecodecamp/drums/Brk_Snr.mp3",
  },
];
